spring:
  application:
    name: ${APP_NAME:springboot-service}

  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: ${JPA_DIALECT:org.hibernate.dialect.H2Dialect}

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-change-this-in-production-must-be-at-least-256-bits}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.example: ${APP_LOG_LEVEL:DEBUG}
    org.springframework.web: ${SPRING_WEB_LOG_LEVEL:DEBUG}
  file:
    name: ${LOG_FILE:/var/log/springboot-service/application.log}
    max-size: 10MB
    max-history: 30

# 애플리케이션 커스텀 설정
app:
  version: ${APP_VERSION:1.2.0}
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:8080}
    allowed-methods: ${CORS_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allow-credentials: ${CORS_CREDENTIALS:true}
